services:
  sandstorm-logger:
    container_name: sandstorm-logger
    build:
      context: .
      network: host
    restart: unless-stopped
    network_mode: host
    # environment:
      # CONFIG_FILE: /app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      # - /path/to/Insurgency/Saved/Logs/Insurgency.log:/app/logs/Insurgency.log:ro
